# Generated by Django 2.2.9 on 2020-03-01 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
        ('photographyspots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='photography_spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='photographyspots.PhotographySpot'),
        ),
    ]
