# Generated by Django 2.2.9 on 2020-03-02 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographyspots', '0002_remove_photographyspot_images'),
        ('images', '0002_image_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
