# Generated by Django 2.2.9 on 2020-03-18 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotographySpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50, unique=True)),
                ('location_description', models.CharField(blank=True, max_length=400)),
                ('location_image', models.CharField(blank=True, max_length=200)),
                ('city', models.ForeignKey(default='City', on_delete=django.db.models.deletion.CASCADE, related_name='photographyspots', to='cities.City')),
            ],
        ),
    ]
